#!/bin/bash
echo  "Updating WAS, please wait."
cd  ~
cd was
git checkout master
git pull
cd backend
npm install
rm -rf dist
npm run build
npx sequelize db:migrate
#npx sequelize db:seed
pm2 restart all

echo  "Update finished. Enjoy!"
